// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-mHjktGVHVGxgfRlpM9L74dpvlMDxhNc',
    appId: '1:680487708451:web:9943e27751e7ed6aa80e96',
    messagingSenderId: '680487708451',
    projectId: 'urbanflooding-1ee2b',
    authDomain: 'urbanflooding-1ee2b.firebaseapp.com',
    storageBucket: 'urbanflooding-1ee2b.firebasestorage.app',
    measurementId: 'G-E3X8JF3D7Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCg6F1ni6Tpw2nR9Q1AULNWXwLDXhdvHWA',
    appId: '1:680487708451:android:245ecd311315a977a80e96',
    messagingSenderId: '680487708451',
    projectId: 'urbanflooding-1ee2b',
    storageBucket: 'urbanflooding-1ee2b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpWNts2UwOaHR33AOMoIuzxdryhgo2ehs',
    appId: '1:680487708451:ios:84ecd5726596a3b3a80e96',
    messagingSenderId: '680487708451',
    projectId: 'urbanflooding-1ee2b',
    storageBucket: 'urbanflooding-1ee2b.firebasestorage.app',
    iosBundleId: 'com.example.floodwatchapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpWNts2UwOaHR33AOMoIuzxdryhgo2ehs',
    appId: '1:680487708451:ios:84ecd5726596a3b3a80e96',
    messagingSenderId: '680487708451',
    projectId: 'urbanflooding-1ee2b',
    storageBucket: 'urbanflooding-1ee2b.firebasestorage.app',
    iosBundleId: 'com.example.floodwatchapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-mHjktGVHVGxgfRlpM9L74dpvlMDxhNc',
    appId: '1:680487708451:web:cb61cf7aabd1f04ea80e96',
    messagingSenderId: '680487708451',
    projectId: 'urbanflooding-1ee2b',
    authDomain: 'urbanflooding-1ee2b.firebaseapp.com',
    storageBucket: 'urbanflooding-1ee2b.firebasestorage.app',
    measurementId: 'G-7WW1ZKZ8T1',
  );
}
