// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ7Ky9bQHNIh--vbdpPYOEUPJ9P07fcmg',
    appId: '1:695214659311:web:379485d30210ae2c5aed1a',
    messagingSenderId: '695214659311',
    projectId: 'floodwatch-trivandrum',
    authDomain: 'floodwatch-trivandrum.firebaseapp.com',
    storageBucket: 'floodwatch-trivandrum.firebasestorage.app',
    measurementId: 'G-R333WTK6Z1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0G72QpLBXBIZ2vjUgknWBnScp1B78enw',
    appId: '1:695214659311:android:8fcb94f99d49ca945aed1a',
    messagingSenderId: '695214659311',
    projectId: 'floodwatch-trivandrum',
    storageBucket: 'floodwatch-trivandrum.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbrAzlLcwgKz5e7hlFJcg_AjNfoCVsXeE',
    appId: '1:695214659311:ios:f0e480c1ed6981355aed1a',
    messagingSenderId: '695214659311',
    projectId: 'floodwatch-trivandrum',
    storageBucket: 'floodwatch-trivandrum.firebasestorage.app',
    iosBundleId: 'com.example.floodwatchapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbrAzlLcwgKz5e7hlFJcg_AjNfoCVsXeE',
    appId: '1:695214659311:ios:f0e480c1ed6981355aed1a',
    messagingSenderId: '695214659311',
    projectId: 'floodwatch-trivandrum',
    storageBucket: 'floodwatch-trivandrum.firebasestorage.app',
    iosBundleId: 'com.example.floodwatchapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQ7Ky9bQHNIh--vbdpPYOEUPJ9P07fcmg',
    appId: '1:695214659311:web:2db68bcd3e032e325aed1a',
    messagingSenderId: '695214659311',
    projectId: 'floodwatch-trivandrum',
    authDomain: 'floodwatch-trivandrum.firebaseapp.com',
    storageBucket: 'floodwatch-trivandrum.firebasestorage.app',
    measurementId: 'G-BC6D3XF1W8',
  );
}
